from typing import Annotated, Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


class SandboxState(BaseModel):
    messages: Annotated[Sequence[BaseMessage], add_messages] = Field(default=[])
    input: str = Field(default="")
    python_script: str = Field(
        default="", description="Python script generated by the LLM"
    )
    script_result: str = Field(default="", description="Result of the script execution")
    image_result: str = Field(default="", description="Base64 encoded image")
    error: str = Field(
        default="", description="Error message if the script execution fails"
    )
